<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CountriesListData extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        //

        $countries = [
            ['name' => 'أفغانستان', 'name_en' => 'Afghanistan', 'code' => '93'],
            ['name' => 'ألبانيا', 'name_en' => 'Albania', 'code' => '355'],
            ['name' => 'الجزائر', 'name_en' => 'Algeria', 'code' => '213'],
            ['name' => 'ساموا الأمريكية', 'name_en' => 'American Samoa', 'code' => '1-684'],
            ['name' => 'أندورا', 'name_en' => 'Andorra', 'code' => '376'],
            ['name' => 'أنجولا', 'name_en' => 'Angola', 'code' => '244'],
            ['name' => 'أنجويلا', 'name_en' => 'Anguilla', 'code' => '1-264'],
            ['name' => 'القطب الجنوبي', 'name_en' => 'Antarctica', 'code' => '672'],
            ['name' => 'أنتيجوا وبربودا', 'name_en' => 'Antigua and Barbuda', 'code' => '1-268'],
            ['name' => 'الأرجنتين', 'name_en' => 'Argentina', 'code' => '54'],
            ['name' => 'أرمينيا', 'name_en' => 'Armenia', 'code' => '374'],
            ['name' => 'آروبا', 'name_en' => 'Aruba', 'code' => '297'],
            ['name' => 'أستراليا', 'name_en' => 'Australia', 'code' => '61'],
            ['name' => 'النمسا', 'name_en' => 'Austria', 'code' => '43'],
            ['name' => 'أذربيجان', 'name_en' => 'Azerbaijan', 'code' => '994'],
            ['name' => 'الباهاما', 'name_en' => 'Bahamas', 'code' => '1-242'],
            ['name' => 'البحرين', 'name_en' => 'Bahrain', 'code' => '973'],
            ['name' => 'بنجلاديش', 'name_en' => 'Bangladesh', 'code' => '880'],
            ['name' => 'بربادوس', 'name_en' => 'Barbados', 'code' => '1-246'],
            ['name' => 'روسيا البيضاء', 'name_en' => 'Belarus', 'code' => '375'],
            ['name' => 'بلجيكا', 'name_en' => 'Belgium', 'code' => '32'],
            ['name' => 'بليز', 'name_en' => 'Belize', 'code' => '501'],
            ['name' => 'بنين', 'name_en' => 'Benin', 'code' => '229'],
            ['name' => 'برمودا', 'name_en' => 'Bermuda', 'code' => '1-441'],
            ['name' => 'بوتان', 'name_en' => 'Bhutan', 'code' => '975'],
            ['name' => 'بوليفيا', 'name_en' => 'Bolivia', 'code' => '591'],
            ['name' => 'البوسنة والهرسك', 'name_en' => 'Bosnia and Herzegovina', 'code' => '387'],
            ['name' => 'بتسوانا', 'name_en' => 'Botswana', 'code' => '267'],
            ['name' => 'البرازيل', 'name_en' => 'Brazil', 'code' => '55'],
            ['name' => 'المحيط الهندي البريطاني', 'name_en' => 'British Indian Ocean Territory', 'code' => '246'],
            ['name' => 'جزر فرجين البريطانية', 'name_en' => 'British Virgin Islands', 'code' => '1-284'],
            ['name' => 'بروناي', 'name_en' => 'Brunei', 'code' => '673'],
            ['name' => 'بلغاريا', 'name_en' => 'Bulgaria', 'code' => '359'],
            ['name' => 'بوركينا فاسو', 'name_en' => 'Burkina Faso', 'code' => '226'],
            ['name' => 'بوروندي', 'name_en' => 'Burundi', 'code' => '257'],
            ['name' => 'كمبوديا', 'name_en' => 'Cambodia', 'code' => '855'],
            ['name' => 'الكاميرون', 'name_en' => 'Cameroon', 'code' => '237'],
            ['name' => 'كندا', 'name_en' => 'Canada', 'code' => '1'],
            ['name' => 'الرأس الأخضر', 'name_en' => 'Cape Verde', 'code' => '238'],
            ['name' => 'جزر الكايمن', 'name_en' => 'Cayman Islands', 'code' => '1-345'],
            ['name' => 'جمهورية افريقيا الوسطى', 'name_en' => 'Central African Republic', 'code' => '236'],
            ['name' => 'تشاد', 'name_en' => 'Chad', 'code' => '235'],
            ['name' => 'شيلي', 'name_en' => 'Chile', 'code' => '56'],
            ['name' => 'الصين', 'name_en' => 'China', 'code' => '86'],
            ['name' => 'جزيرة الكريسماس', 'name_en' => 'Christmas Island', 'code' => '61'],
            ['name' => 'جزر كوكوس', 'name_en' => 'Cocos Islands', 'code' => '61'],
            ['name' => 'كولومبيا', 'name_en' => 'Colombia', 'code' => '57'],
            ['name' => 'جزر القمر', 'name_en' => 'Comoros', 'code' => '269'],
            ['name' => 'جزر كوك', 'name_en' => 'Cook Islands', 'code' => '682'],
            ['name' => 'كوستاريكا', 'name_en' => 'Costa Rica', 'code' => '506'],
            ['name' => 'كرواتيا', 'name_en' => 'Croatia', 'code' => '385'],
            ['name' => 'كوبا', 'name_en' => 'Cuba', 'code' => '53'],
            ['name' => 'كوراساو', 'name_en' => 'Curacao', 'code' => '599'],
            ['name' => 'قبرص', 'name_en' => 'Cyprus', 'code' => '357'],
            ['name' => 'جمهورية التشيك', 'name_en' => 'Czech Republic', 'code' => '420'],
            ['name' => 'جمهورية الكونغو الديمقراطية', 'name_en' => 'Democratic Republic of the Congo', 'code' => '243'],
            ['name' => 'جيبوتي', 'name_en' => 'Denmark', 'code' => '45'],
            ['name' => 'جيبوتي', 'name_en' => 'Djibouti', 'code' => '253'],
            ['name' => 'دومينيكا', 'name_en' => 'Dominica', 'code' => '1-767'],
            ['name' => 'تيمور الشرقية', 'name_en' => 'East Timor', 'code' => '670'],
            ['name' => 'الاكوادور', 'name_en' => 'Ecuador', 'code' => '593'],
            ['name' => 'مصر', 'name_en' => 'Egypt', 'code' => '20'],
            ['name' => 'السلفادور', 'name_en' => 'El Salvador', 'code' => '503'],
            ['name' => 'غينيا الاستوائية', 'name_en' => 'Equatorial Guinea', 'code' => '240'],
            ['name' => 'اريتريا', 'name_en' => 'Eritrea', 'code' => '291'],
            ['name' => 'استونيا', 'name_en' => 'Estonia', 'code' => '372'],
            ['name' => 'اثيوبيا', 'name_en' => 'Ethiopia', 'code' => '251'],
            ['name' => 'جزر فوكلاند', 'name_en' => 'Falkland Islands', 'code' => '500'],
            ['name' => 'جزر فارو', 'name_en' => 'Faroe Islands', 'code' => '298'],
            ['name' => 'فيجي', 'name_en' => 'Fiji', 'code' => '679'],
            ['name' => 'فنلندا', 'name_en' => 'Finland', 'code' => '358'],
            ['name' => 'فرنسا', 'name_en' => 'France', 'code' => '33'],
            ['name' => 'بولينيزيا الفرنسية', 'name_en' => 'French Polynesia', 'code' => '689'],
            ['name' => 'الجابون', 'name_en' => 'Gabon', 'code' => '241'],
            ['name' => 'غامبيا', 'name_en' => 'Gambia', 'code' => '220'],
            ['name' => 'جورجيا', 'name_en' => 'Georgia', 'code' => '995'],
            ['name' => 'ألمانيا', 'name_en' => 'Germany', 'code' => '49'],
            ['name' => 'غانا', 'name_en' => 'Ghana', 'code' => '233'],
            ['name' => 'جبل طارق', 'name_en' => 'Gibraltar', 'code' => '350'],
            ['name' => 'اليونان', 'name_en' => 'Greece', 'code' => '30'],
            ['name' => 'جرينلاند', 'name_en' => 'Greenland', 'code' => '299'],
            ['name' => 'جرينادا', 'name_en' => 'Grenada', 'code' => '1-473'],
            ['name' => 'جوام', 'name_en' => 'Guam', 'code' => '1-671'],
            ['name' => 'جواتيمالا', 'name_en' => 'Guatemala', 'code' => '502'],
            ['name' => 'غيرنزي', 'name_en' => 'Guernsey', 'code' => '44-1481'],
            ['name' => 'غينيا', 'name_en' => 'Guinea', 'code' => '224'],
            ['name' => 'غينيا بيساو', 'name_en' => 'Guinea-Bissau', 'code' => '245'],
            ['name' => 'غيانا', 'name_en' => 'Guyana', 'code' => '592'],
            ['name' => 'هايتي', 'name_en' => 'Haiti', 'code' => '509'],
            ['name' => 'هندوراس', 'name_en' => 'Honduras', 'code' => '504'],
            ['name' => 'هونج كونج الصينية', 'name_en' => 'Hong Kong', 'code' => '852'],
            ['name' => 'المجر', 'name_en' => 'Hungary', 'code' => '36'],
            ['name' => 'أيسلندا', 'name_en' => 'Iceland', 'code' => '354'],
            ['name' => 'الهند', 'name_en' => 'India', 'code' => '91'],
            ['name' => 'اندونيسيا', 'name_en' => 'Indonesia', 'code' => '62'],
            ['name' => 'ايران', 'name_en' => 'Iran', 'code' => '98'],
            ['name' => 'العراق', 'name_en' => 'Iraq', 'code' => '964'],
            ['name' => 'أيرلندا', 'name_en' => 'Ireland', 'code' => '353'],
            ['name' => 'جزيرة مان', 'name_en' => 'Isle of Man', 'code' => '44-1624'],
            ['name' => 'اسرائيل', 'name_en' => 'Israel', 'code' => '972'],
            ['name' => 'ايطاليا', 'name_en' => 'Italy', 'code' => '39'],
            ['name' => 'ساحل العاج', 'name_en' => 'Ivory Coast', 'code' => '225'],
            ['name' => 'جامايكا', 'name_en' => 'Jamaica', 'code' => '1-876'],
            ['name' => 'اليابان', 'name_en' => 'Japan', 'code' => '81'],
            ['name' => 'جيرسي', 'name_en' => 'Jersey', 'code' => '44-1534'],
            ['name' => 'الأردن', 'name_en' => 'Jordan', 'code' => '962'],
            ['name' => 'كازاخستان', 'name_en' => 'Kazakhstan', 'code' => '7'],
            ['name' => 'كينيا', 'name_en' => 'Kenya', 'code' => '254'],
            ['name' => 'كيريباتي', 'name_en' => 'Kiribati', 'code' => '686'],
            ['name' => 'كوسوفو', 'name_en' => 'Kosovo', 'code' => '383'],
            ['name' => 'الكويت', 'name_en' => 'Kuwait', 'code' => '965'],
            ['name' => 'قرغيزستان', 'name_en' => 'Kyrgyzstan', 'code' => '996'],
            ['name' => 'لاوس', 'name_en' => 'Laos', 'code' => '856'],
            ['name' => 'لاتفيا', 'name_en' => 'Latvia', 'code' => '371'],
            ['name' => 'لبنان', 'name_en' => 'Lebanon', 'code' => '961'],
            ['name' => 'ليسوتو', 'name_en' => 'Lesotho', 'code' => '266'],
            ['name' => 'ليبيريا', 'name_en' => 'Liberia', 'code' => '231'],
            ['name' => 'ليبيا', 'name_en' => 'Libya', 'code' => '218'],
            ['name' => 'ليختنشتاين', 'name_en' => 'Liechtenstein', 'code' => '423'],
            ['name' => 'ليتوانيا', 'name_en' => 'Lithuania', 'code' => '370'],
            ['name' => 'لوكسمبورج', 'name_en' => 'Luxembourg', 'code' => '352'],
            ['name' => 'ماكاو الصينية', 'name_en' => 'Macau', 'code' => '853'],
            ['name' => 'مقدونيا', 'name_en' => 'Macedonia', 'code' => '389'],
            ['name' => 'مدغشقر', 'name_en' => 'Madagascar', 'code' => '261'],
            ['name' => 'ملاوي', 'name_en' => 'Malawi', 'code' => '265'],
            ['name' => 'ماليزيا', 'name_en' => 'Malaysia', 'code' => '60'],
            ['name' => 'جزر الملديف', 'name_en' => 'Maldives', 'code' => '960'],
            ['name' => 'مالي', 'name_en' => 'Mali', 'code' => '223'],
            ['name' => 'مالطا', 'name_en' => 'Malta', 'code' => '356'],
            ['name' => 'جزر المارشال', 'name_en' => 'Marshall Islands', 'code' => '692'],
            ['name' => 'موريتانيا', 'name_en' => 'Mauritania', 'code' => '222'],
            ['name' => 'موريشيوس', 'name_en' => 'Mauritius', 'code' => '230'],
            ['name' => 'مايوت', 'name_en' => 'Mayotte', 'code' => '262'],
            ['name' => 'المكسيك', 'name_en' => 'Mexico', 'code' => '52'],
            ['name' => 'ميكرونيزيا', 'name_en' => 'Micronesia', 'code' => '691'],
            ['name' => 'مولدافيا', 'name_en' => 'Moldova', 'code' => '373'],
            ['name' => 'موناكو', 'name_en' => 'Monaco', 'code' => '377'],
            ['name' => 'منغوليا', 'name_en' => 'Mongolia', 'code' => '976'],
            ['name' => 'الجبل الأسود', 'name_en' => 'Montenegro', 'code' => '382'],
            ['name' => 'مونتسرات', 'name_en' => 'Montserrat', 'code' => '1-664'],
            ['name' => 'المغرب', 'name_en' => 'Morocco', 'code' => '212'],
            ['name' => 'موزمبيق', 'name_en' => 'Mozambique', 'code' => '258'],
            ['name' => 'ميانمار', 'name_en' => 'Myanmar', 'code' => '95'],
            ['name' => 'ناميبيا', 'name_en' => 'Namibia', 'code' => '264'],
            ['name' => 'نورو', 'name_en' => 'Nauru', 'code' => '674'],
            ['name' => 'نيبال', 'name_en' => 'Nepal', 'code' => '977'],
            ['name' => 'هولندا', 'name_en' => 'Netherlands', 'code' => '31'],
            ['name' => 'أرمينيا', 'name_en' => 'Netherlands Antilles', 'code' => '599'],
            ['name' => 'كاليدونيا الجديدة', 'name_en' => 'New Caledonia', 'code' => '687'],
            ['name' => 'نيوزيلاندا', 'name_en' => 'New Zealand', 'code' => '64'],
            ['name' => 'نيكاراجوا', 'name_en' => 'Nicaragua', 'code' => '505'],
            ['name' => 'النيجر', 'name_en' => 'Niger', 'code' => '227'],
            ['name' => 'نيجيريا', 'name_en' => 'Nigeria', 'code' => '234'],
            ['name' => 'نورو', 'name_en' => 'Niue', 'code' => '683'],
            ['name' => 'كوريا الشمالية', 'name_en' => 'North Korea', 'code' => '850'],
            ['name' => 'جزر ماريانا الشمالية', 'name_en' => 'Northern Mariana Islands', 'code' => '1-670'],
            ['name' => 'النرويج', 'name_en' => 'Norway', 'code' => '47'],
            ['name' => 'عمان', 'name_en' => 'Oman', 'code' => '968'],
            ['name' => 'باكستان', 'name_en' => 'Pakistan', 'code' => '92'],
            ['name' => 'بالاو', 'name_en' => 'Palau', 'code' => '680'],
            ['name' => 'فلسطين', 'name_en' => 'Palestine', 'code' => '970'],
            ['name' => 'بنما', 'name_en' => 'Panama', 'code' => '507'],
            ['name' => 'بابوا غينيا الجديدة', 'name_en' => 'Papua New Guinea', 'code' => '675'],
            ['name' => 'باراجواي', 'name_en' => 'Paraguay', 'code' => '595'],
            ['name' => 'بيرو', 'name_en' => 'Peru', 'code' => '51'],
            ['name' => 'الفيلبين', 'name_en' => 'Philippines', 'code' => '63'],
            ['name' => 'بتكايرن', 'name_en' => 'Pitcairn', 'code' => '64'],
            ['name' => 'بولندا', 'name_en' => 'Poland', 'code' => '48'],
            ['name' => 'البرتغال', 'name_en' => 'Portugal', 'code' => '351'],
            ['name' => 'قطر', 'name_en' => 'Qatar', 'code' => '974'],
            ['name' => 'الكونغو - برازافيل', 'name_en' => 'Republic of the Congo', 'code' => '242'],
            ['name' => 'روينيون', 'name_en' => 'Reunion', 'code' => '262'],
            ['name' => 'رومانيا', 'name_en' => 'Romania', 'code' => '40'],
            ['name' => 'روسيا', 'name_en' => 'Russia', 'code' => '7'],
            ['name' => 'رواندا', 'name_en' => 'Rwanda', 'code' => '250'],
            ['name' => 'سان بارتيلمي', 'name_en' => 'Saint Barthelemy', 'code' => '590'],
            ['name' => 'سانت هيلنا', 'name_en' => 'Saint Helena', 'code' => '290'],
            ['name' => 'سانت كيتس ونيفيس', 'name_en' => 'Saint Kitts and Nevis', 'code' => '1-869'],
            ['name' => 'سانت لوسيا', 'name_en' => 'Saint Lucia', 'code' => '1-758'],
            ['name' => 'سانت مارتين', 'name_en' => 'Saint Martin', 'code' => '590'],
            ['name' => 'سانت بيير وميكولون', 'name_en' => 'Saint Pierre and Miquelon', 'code' => '508'],
            ['name' => 'سانت فنسنت وغرنادين', 'name_en' => 'Saint Vincent and the Grenadines', 'code' => '1-784'],
            ['name' => 'ساموا', 'name_en' => 'Samoa', 'code' => '685'],
            ['name' => 'سان مارينو', 'name_en' => 'San Marino', 'code' => '378'],
            ['name' => 'ساو تومي وبرينسيبي', 'name_en' => 'Sao Tome and Principe', 'code' => '239'],
            ['name' => 'المملكة العربية السعودية', 'name_en' => 'Saudi Arabia', 'code' => '966'],
            ['name' => 'السنغال', 'name_en' => 'Senegal', 'code' => '221'],
            ['name' => 'صربيا', 'name_en' => 'Serbia', 'code' => '381'],
            ['name' => 'سيشل', 'name_en' => 'Seychelles', 'code' => '248'],
            ['name' => 'سيراليون', 'name_en' => 'Sierra Leone', 'code' => '232'],
            ['name' => 'سنغافورة', 'name_en' => 'Singapore', 'code' => '65'],
            ['name' => 'سينت مارتن', 'name_en' => 'Sint Maarten', 'code' => '1-721'],
            ['name' => 'سلوفاكيا', 'name_en' => 'Slovakia', 'code' => '421'],
            ['name' => 'سلوفينيا', 'name_en' => 'Slovenia', 'code' => '386'],
            ['name' => 'جزر سليمان', 'name_en' => 'Solomon Islands', 'code' => '677'],
            ['name' => 'الصومال', 'name_en' => 'Somalia', 'code' => '252'],
            ['name' => 'جمهورية جنوب افريقيا', 'name_en' => 'South Africa', 'code' => '27'],
            ['name' => 'كوريا الجنوبية', 'name_en' => 'South Korea', 'code' => '82'],
            ['name' => 'جنوب السودان', 'name_en' => 'South Sudan', 'code' => '211'],
            ['name' => 'أسبانيا', 'name_en' => 'Spain', 'code' => '34'],
            ['name' => 'سريلانكا', 'name_en' => 'Sri Lanka', 'code' => '94'],
            ['name' => 'السودان', 'name_en' => 'Sudan', 'code' => '249'],
            ['name' => 'سورينام', 'name_en' => 'Suriname', 'code' => '597'],
            ['name' => 'سفالبارد وجان مايان', 'name_en' => 'Svalbard and Jan Mayen', 'code' => '47'],
            ['name' => 'سوازيلاند', 'name_en' => 'Swaziland', 'code' => '268'],
            ['name' => 'السويد', 'name_en' => 'Sweden', 'code' => '46'],
            ['name' => 'سويسرا', 'name_en' => 'Switzerland', 'code' => '41'],
            ['name' => 'سوريا', 'name_en' => 'Syria', 'code' => '963'],
            ['name' => 'تايوان', 'name_en' => 'Taiwan', 'code' => '886'],
            ['name' => 'طاجكستان', 'name_en' => 'Tajikistan', 'code' => '992'],
            ['name' => 'تانزانيا', 'name_en' => 'Tanzania', 'code' => '255'],
            ['name' => 'تايلند', 'name_en' => 'Thailand', 'code' => '66'],
            ['name' => 'توجو', 'name_en' => 'Togo', 'code' => '228'],
            ['name' => 'توكيلو', 'name_en' => 'Tokelau', 'code' => '690'],
            ['name' => 'تونجا', 'name_en' => 'Tonga', 'code' => '676'],
            ['name' => 'ترينيداد وتوباغو', 'name_en' => 'Trinidad and Tobago', 'code' => '1-868'],
            ['name' => 'تونس', 'name_en' => 'Tunisia', 'code' => '216'],
            ['name' => 'تركيا', 'name_en' => 'Turkey', 'code' => '90'],
            ['name' => 'تركمانستان', 'name_en' => 'Turkmenistan', 'code' => '993'],
            ['name' => 'جزر الترك وجايكوس', 'name_en' => 'Turks and Caicos Islands', 'code' => '1-649'],
            ['name' => 'توفالو', 'name_en' => 'Tuvalu', 'code' => '688'],
            ['name' => 'جزر فرجين الأمريكية', 'name_en' => 'U.S. Virgin Islands', 'code' => '1-340'],
            ['name' => 'أوغندا', 'name_en' => 'Uganda', 'code' => '256'],
            ['name' => 'أوكرانيا', 'name_en' => 'Ukraine', 'code' => '380'],
            ['name' => 'الامارات العربية المتحدة', 'name_en' => 'United Arab Emirates', 'code' => '971'],
            ['name' => 'المملكة المتحدة', 'name_en' => 'United Kingdom', 'code' => '44'],
            ['name' => 'الولايات المتحدة الأمريكية', 'name_en' => 'United States', 'code' => '1'],
            ['name' => 'أورجواي', 'name_en' => 'Uruguay', 'code' => '598'],
            ['name' => 'أوزبكستان', 'name_en' => 'Uzbekistan', 'code' => '998'],
            ['name' => 'فانواتو', 'name_en' => 'Vanuatu', 'code' => '678'],
            ['name' => 'الفاتيكان', 'name_en' => 'Vatican', 'code' => '379'],
            ['name' => 'فنزويلا', 'name_en' => 'Venezuela', 'code' => '58'],
            ['name' => 'فيتنام', 'name_en' => 'Vietnam', 'code' => '84'],
            ['name' => 'جزر والس وفوتونا', 'name_en' => 'Wallis and Futuna', 'code' => '681'],
            ['name' => 'الصحراء الغربية', 'name_en' => 'Western Sahara', 'code' => '212'],
            ['name' => 'اليمن', 'name_en' => 'Yemen', 'code' => '967'],
            ['name' => 'زامبيا', 'name_en' => 'Zambia', 'code' => '260'],
            ['name' => 'زيمبابوي', 'name_en' => 'Zimbabwe', 'code' => '263'],

        ];

        DB::table('countries')->insert($countries);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
        DB::table('countries')->delete();
    }
}
