<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class SeedProjectPageData extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        //

        $main_page = [
            [
                'page_name' => 'main_page',
                'page_name_text' => 'الصفحة الرئيسية',
                'section_name' => 'welcoming',
                'section_name_text' => 'لماذا منصة المهندسين',
                'paragraph_name' => 'why_us',
                'paragraph_name_text' => 'فقرة لماذا منصة المهندسين',
                'content_ar' => "خدمات مكاتب هندسية المعتمدة من الهئية السعودية للمهندسين ذات العلاقة\r\nالمهندسون المستقلون المرخصين من الهيئة السعودية للمهندسين\r\nخبراء التحكيم الهندسي المرخصين من الهيئة السعودية للمهندسين\r\nاختيار مقدم الخدمة بناء علي السعر والتقييم والخبرات السابقة واختيار العرض المناسب\r\nأخذ تصور عام من قبل المستفيد من خلال منصة مهندسون ومعرفة وضع السوق",
                'content_en' => "خدمات مكاتب هندسية المعتمدة من الهئية السعودية للمهندسين ذات العلاقة\r\nالمهندسون المستقلون المرخصين من الهيئة السعودية للمهندسين\r\nخبراء التحكيم الهندسي المرخصين من الهيئة السعودية للمهندسين\r\nاختيار مقدم الخدمة بناء علي السعر والتقييم والخبرات السابقة واختيار العرض المناسب\r\nأخذ تصور عام من قبل المستفيد من خلال منصة مهندسون ومعرفة وضع السوق",
            ],
            [
                'page_name' => 'main_page',
                'page_name_text' => 'الصفحة الرئيسية',
                'section_name' => 'main_services',
                'section_name_text' => 'الخدمات',
                'paragraph_name' => 'main_services_project',
                'paragraph_name_text' => 'تنفيذ مشروع',
                'content_ar' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في ',
                'content_en' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في ',
            ],
            [
                'page_name' => 'main_page',
                'page_name_text' => 'الصفحة الرئيسية',
                'section_name' => 'main_services',
                'section_name_text' => 'الخدمات',
                'paragraph_name' => 'main_services_consult',
                'paragraph_name_text' => 'طلب استشارة',
                'content_ar' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في ',
                'content_en' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في ',
            ],
            [
                'page_name' => 'main_page',
                'page_name_text' => 'الصفحة الرئيسية',
                'section_name' => 'main_services',
                'section_name_text' => 'الخدمات',
                'paragraph_name' => 'main_services_judge',
                'paragraph_name_text' => 'تحكيم بين طرفين',
                'content_ar' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في ',
                'content_en' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في ',
            ],
            [
                'page_name' => 'main_page',
                'page_name_text' => 'الصفحة الرئيسية',
                'section_name' => 'main_services',
                'section_name_text' => 'الخدمات',
                'paragraph_name' => 'main_services_visit',
                'paragraph_name_text' => 'طلب زيارة موقع',
                'content_ar' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في ',
                'content_en' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في ',
            ],
            [
                'page_name' => 'main_page',
                'page_name_text' => 'الصفحة الرئيسية',
                'section_name' => 'main_services',
                'section_name_text' => 'الخدمات',
                'paragraph_name' => 'main_services_licence',
                'paragraph_name_text' => 'طلب ترخيص',
                'content_ar' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في ',
                'content_en' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في ',
            ],
            [
                'page_name' => 'main_page',
                'page_name_text' => 'الصفحة الرئيسية',
                'section_name' => 'how_we_work',
                'section_name_text' => 'كيف نعمل',
                'paragraph_name' => 'step_1',
                'paragraph_name_text' => 'الاشتراك',
                'content_ar' => 'ناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام',
                'content_en' => 'ناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام',
            ],
            [
                'page_name' => 'main_page',
                'page_name_text' => 'الصفحة الرئيسية',
                'section_name' => 'how_we_work',
                'section_name_text' => 'كيف نعمل',
                'paragraph_name' => 'step_2',
                'paragraph_name_text' => 'إضافة الطلب',
                'content_ar' => 'ناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام',
                'content_en' => 'ناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام',
            ],
            [
                'page_name' => 'main_page',
                'page_name_text' => 'الصفحة الرئيسية',
                'section_name' => 'how_we_work',
                'section_name_text' => 'كيف نعمل',
                'paragraph_name' => 'step_3',
                'paragraph_name_text' => 'تقديم العروض',
                'content_ar' => 'ناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام',
                'content_en' => 'ناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام',
            ],
            [
                'page_name' => 'main_page',
                'page_name_text' => 'الصفحة الرئيسية',
                'section_name' => 'how_we_work',
                'section_name_text' => 'كيف نعمل',
                'paragraph_name' => 'step_4',
                'paragraph_name_text' => 'تنفذ المشروع',
                'content_ar' => 'ناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام',
                'content_en' => 'ناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام',
            ],
            [
                'page_name' => 'main_page',
                'page_name_text' => 'الصفحة الرئيسية',
                'section_name' => 'how_we_work',
                'section_name_text' => 'كيف نعمل',
                'paragraph_name' => 'step_5',
                'paragraph_name_text' => 'تسليم المشروع',
                'content_ar' => 'ناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام',
                'content_en' => 'ناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام',
            ],
            [
                'page_name' => 'main_page',
                'page_name_text' => 'الصفحة الرئيسية',
                'section_name' => 'statistics',
                'section_name_text' => 'الإحصائيات',
                'paragraph_name' => 'count_consults',
                'paragraph_name_text' => 'استشارة - الإحصائيات',
                'content_ar' => '250',
                'content_en' => '250',
            ],
            [
                'page_name' => 'main_page',
                'page_name_text' => 'الصفحة الرئيسية',
                'section_name' => 'statistics',
                'section_name_text' => 'الإحصائيات',
                'paragraph_name' => 'count_freelancers',
                'paragraph_name_text' => 'المستقلين - الإحصائيات',
                'content_ar' => '3500',
                'content_en' => '3500',
            ],
            [
                'page_name' => 'main_page',
                'page_name_text' => 'الصفحة الرئيسية',
                'section_name' => 'statistics',
                'section_name_text' => 'الإحصائيات',
                'paragraph_name' => 'count_companies',
                'paragraph_name_text' => 'شركة هندسية - الإحصائيات',
                'content_ar' => '500',
                'content_en' => '500',
            ],
            [
                'page_name' => 'main_page',
                'page_name_text' => 'الصفحة الرئيسية',
                'section_name' => 'statistics',
                'section_name_text' => 'الإحصائيات',
                'paragraph_name' => 'count_projectsdone',
                'paragraph_name_text' => 'مشروع - الإحصائيات',
                'content_ar' => '4500',
                'content_en' => '4500',
            ],
        ];

        DB::table('website_content')->insert($main_page);

        $project_page = [
            [
                'page_name' => 'project',
                'page_name_text' => 'تنفيذ مشروع',
                'section_name' => 'welcoming',
                'section_name_text' => 'قسم الترحيب',
                'paragraph_name' => 'heading_title',
                'paragraph_name_text' => 'الجملة الرئيسية',
                'content_ar' => 'هيا بنا نتعرف سويا على خدمة تنفيذ مشروع ',
                'content_en' => 'هيا بنا نتعرف سويا على خدمة تنفيذ مشروع ',
                'icon_name' => NULL,
            ],
            [
                'page_name' => 'project',
                'page_name_text' => 'تنفيذ مشروع',
                'section_name' => 'welcoming',
                'section_name_text' => 'قسم الترحيب',
                'paragraph_name' => 'heading_title2',
                'paragraph_name_text' => 'الفقرة الرئيسية - العنوان',
                'content_ar' => 'معنا..تحول أفكارك وخيالاتك الى واقع مذهل :)',
                'content_en' => 'معنا..تحول أفكارك وخيالاتك الى واقع مذهل :)',
                'icon_name' => NULL,
            ],
            [
                'page_name' => 'project',
                'page_name_text' => 'تنفيذ مشروع',
                'section_name' => 'welcoming',
                'section_name_text' => 'قسم الترحيب',
                'paragraph_name' => 'welcome_para',
                'paragraph_name_text' => 'الفقرة الرئيسية - النص',
                'content_ar' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام طريقة لوريم إيبسوم لأنها تعطي توزيعاَ طبيعياَ -إلى حد ما- ',
                'content_en' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام طريقة لوريم إيبسوم لأنها تعطي توزيعاَ طبيعياَ -إلى حد ما- ',
                'icon_name' => NULL,
            ],
            [
                'page_name' => 'project',
                'page_name_text' => 'تنفيذ مشروع',
                'section_name' => 'section_types',
                'section_name_text' => 'تنفيذ مشروع - انواع المشاريع',
                'paragraph_name' => 'project_type_1',
                'paragraph_name_text' => 'انواع المشاريع',
                'content_ar' => 'مخططات معمارية',
                'content_en' => 'مخططات معمارية',
                'icon_name' => 'icons.project-icon-1',
            ],
            [
                'page_name' => 'project',
                'page_name_text' => 'تنفيذ مشروع',
                'section_name' => 'section_types',
                'section_name_text' => 'تنفيذ مشروع - انواع المشاريع',
                'paragraph_name' => 'project_type_2',
                'paragraph_name_text' => 'انواع المشاريع',
                'content_ar' => 'مخططات سكنية',
                'content_en' => 'مخططات سكنية',
                'icon_name' => 'icons.project-icon-1',
            ],
            [
                'page_name' => 'project',
                'page_name_text' => 'تنفيذ مشروع',
                'section_name' => 'section_types',
                'section_name_text' => 'تنفيذ مشروع - انواع المشاريع',
                'paragraph_name' => 'project_type_3',
                'paragraph_name_text' => 'انواع المشاريع',
                'content_ar' => 'مخططات انشائية',
                'content_en' => 'مخططات انشائية',
                'icon_name' => 'icons.project-icon-1',
            ],
            [
                'page_name' => 'project',
                'page_name_text' => 'تنفيذ مشروع',
                'section_name' => 'section_types',
                'section_name_text' => 'تنفيذ مشروع - انواع المشاريع',
                'paragraph_name' => 'project_type_4',
                'paragraph_name_text' => 'انواع المشاريع',
                'content_ar' => 'مخططات الأمن والسلامة',
                'content_en' => 'مخططات الأمن والسلامة',
                'icon_name' => 'icons.project-icon-2',
            ],
            [
                'page_name' => 'project',
                'page_name_text' => 'تنفيذ مشروع',
                'section_name' => 'section_types',
                'section_name_text' => 'تنفيذ مشروع - انواع المشاريع',
                'paragraph_name' => 'project_type_5',
                'paragraph_name_text' => 'انواع المشاريع',
                'content_ar' => 'مخططات صحيحة ميكانيكية',
                'content_en' => 'مخططات صحيحة ميكانيكية',
                'icon_name' => 'icons.project-icon-1',
            ],
            [
                'page_name' => 'project',
                'page_name_text' => 'تنفيذ مشروع',
                'section_name' => 'section_types',
                'section_name_text' => 'تنفيذ مشروع - انواع المشاريع',
                'paragraph_name' => 'project_type_6',
                'paragraph_name_text' => 'انواع المشاريع',
                'content_ar' => 'تصميم واجهات',
                'content_en' => 'تصميم واجهات',
                'icon_name' => 'icons.project-icon-3',
            ],
            [
                'page_name' => 'project',
                'page_name_text' => 'تنفيذ مشروع',
                'section_name' => 'section_types',
                'section_name_text' => 'تنفيذ مشروع - انواع المشاريع',
                'paragraph_name' => 'project_type_7',
                'paragraph_name_text' => 'انواع المشاريع',
                'content_ar' => 'تصميم واجهات',
                'content_en' => 'تصميم واجهات',
                'icon_name' => 'icons.project-icon-3',
            ],
            [
                'page_name' => 'project',
                'page_name_text' => 'تنفيذ مشروع',
                'section_name' => 'section_types',
                'section_name_text' => 'تنفيذ مشروع - انواع المشاريع',
                'paragraph_name' => 'project_type_8',
                'paragraph_name_text' => 'انواع المشاريع',
                'content_ar' => 'تصميم حدائق',
                'content_en' => 'تصميم حدائق',
                'icon_name' => 'icons.project-icon-1',
            ],
            [
                'page_name' => 'project',
                'page_name_text' => 'تنفيذ مشروع',
                'section_name' => 'section_types',
                'section_name_text' => 'تنفيذ مشروع - انواع المشاريع',
                'paragraph_name' => 'project_type_9',
                'paragraph_name_text' => 'انواع المشاريع',
                'content_ar' => 'تصميم مشاريع كبرى',
                'content_en' => 'تصميم مشاريع كبرى',
                'icon_name' => 'icons.project-icon-1',
            ],
            [
                'page_name' => 'project',
                'page_name_text' => 'تنفيذ مشروع',
                'section_name' => 'section_types',
                'section_name_text' => 'تنفيذ مشروع - انواع المشاريع',
                'paragraph_name' => 'project_type_10',
                'paragraph_name_text' => 'انواع المشاريع',
                'content_ar' => 'إشراف تصميم ملاعب رياضيه',
                'content_en' => 'إشراف تصميم ملاعب رياضيه',
                'icon_name' => 'icons.project-icon-4',
            ],

            [
                'page_name' => 'project',
                'page_name_text' => 'تنفيذ مشروع',
                'section_name' => 'exec_agencies',
                'section_name_text' => 'الجهة المنفذة',
                'paragraph_name' => 'user_type_freelancer',
                'paragraph_name_text' => 'الجهة الاولى',
                'content_ar' => 'مهندسين مستقلين',
                'content_en' => 'مهندسين مستقلين',
                'icon_name' => NULL,
            ],
            [
                'page_name' => 'project',
                'page_name_text' => 'تنفيذ مشروع',
                'section_name' => 'exec_agencies',
                'section_name_text' => 'الجهة المنفذة',
                'paragraph_name' => 'user_type_companies',
                'paragraph_name_text' => 'الجهة الثانية',
                'content_ar' => 'مكاتب هندسية مرخصه',
                'content_en' => 'مكاتب هندسية مرخصه',
                'icon_name' => NULL,
            ],
            [
                'page_name' => 'project',
                'page_name_text' => 'تنفيذ مشروع',
                'section_name' => 'service_features',
                'section_name_text' => 'مميزات الخدمة',
                'paragraph_name' => 'features',
                'paragraph_name_text' => 'الخدمات',
                'content_ar' => "مجموعة كبيرة من المستقلين( مهندسين او مكاتب هندسة) الموثقين والمعتمدين من الهيئة السعودية للمهندسين\r\nمعرض أعمال سابقة يحتوي على مجموعة من اعمال المهندسين او المكاتب الهندسية\r\nمتابعة حالة المشروع  وإمكانية التواصل مع الجهة المنفذة من خلال المنصة\r\nفريق دعم فني وتحكيم في حالة النزاع علي مدار الساعة\r\nطرق دفع ميسره وتناسب الجميع \r\nالمنصة لا تكلف  الزبائن أي عمولة ( العمولات نسبة داخلية مستقبلاً )\r\nإمكانية اغلاق المشروع او الغاءه قبل قبول أي عرض",
                'content_en' => "مجموعة كبيرة من المستقلين( مهندسين او مكاتب هندسة) الموثقين والمعتمدين من الهيئة السعودية للمهندسين\r\nمعرض أعمال سابقة يحتوي على مجموعة من اعمال المهندسين او المكاتب الهندسية\r\nمتابعة حالة المشروع  وإمكانية التواصل مع الجهة المنفذة من خلال المنصة\r\nفريق دعم فني وتحكيم في حالة النزاع علي مدار الساعة\r\nطرق دفع ميسره وتناسب الجميع \r\nالمنصة لا تكلف  الزبائن أي عمولة ( العمولات نسبة داخلية مستقبلاً )\r\nإمكانية اغلاق المشروع او الغاءه قبل قبول أي عرض",
                'icon_name' => NULL,
            ],
            [
                'page_name' => 'project',
                'page_name_text' => 'تنفيذ مشروع',
                'section_name' => 'how_we_work',
                'section_name_text' => 'كيف نعمل',
                'paragraph_name' => 'steps_1',
                'paragraph_name_text' => 'الاشتراك',
                'content_ar' => 'اك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام طريقة لوريم',
                'content_en' => 'اك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام طريقة لوريم',
                'icon_name' => NULL,
            ],
            [
                'page_name' => 'project',
                'page_name_text' => 'تنفيذ مشروع',
                'section_name' => 'how_we_work',
                'section_name_text' => 'كيف نعمل',
                'paragraph_name' => 'steps_2',
                'paragraph_name_text' => 'إضافة الطلب',
                'content_ar' => 'اك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو',
                'content_en' => 'اك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو',
                'icon_name' => NULL,
            ],
            [
                'page_name' => 'project',
                'page_name_text' => 'تنفيذ مشروع',
                'section_name' => 'how_we_work',
                'section_name_text' => 'كيف نعمل',
                'paragraph_name' => 'steps_3',
                'paragraph_name_text' => 'استقبال العروض',
                'content_ar' => 'اك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام طريقة لوريم',
                'content_en' => 'اك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام طريقة لوريم',
                'icon_name' => NULL,
            ],
            [
                'page_name' => 'project',
                'page_name_text' => 'تنفيذ مشروع',
                'section_name' => 'how_we_work',
                'section_name_text' => 'كيف نعمل',
                'paragraph_name' => 'steps_4',
                'paragraph_name_text' => 'قبول عرض',
                'content_ar' => 'اك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في',
                'content_en' => 'اك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في',
                'icon_name' => NULL,
            ],
            [
                'page_name' => 'project',
                'page_name_text' => 'تنفيذ مشروع',
                'section_name' => 'how_we_work',
                'section_name_text' => 'كيف نعمل',
                'paragraph_name' => 'steps_5',
                'paragraph_name_text' => 'بدء التنفيذ',
                'content_ar' => 'اك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في',
                'content_en' => 'اك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في',
                'icon_name' => NULL,
            ],
            [
                'page_name' => 'project',
                'page_name_text' => 'تنفيذ مشروع',
                'section_name' => 'how_we_work',
                'section_name_text' => 'كيف نعمل',
                'paragraph_name' => 'steps_6',
                'paragraph_name_text' => 'استلام المشروع',
                'content_ar' => 'اك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في',
                'content_en' => 'اك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في',
                'icon_name' => NULL,
            ],
            [
                'page_name' => 'project',
                'page_name_text' => 'تنفيذ مشروع',
                'section_name' => 'warning_section',
                'section_name_text' => 'قسم التنبيه',
                'paragraph_name' => 'warning_message',
                'paragraph_name_text' => 'التنبيه',
                'content_ar' => "شهادة ترخيص من البلادية  في حالة طلب ترخيص\r\nعند قبول عرض يجب وضع المبلغ المقبول في المحظفة لدي المنصة لضمان حق الطرفين",
                'content_en' => "شهادة ترخيص من البلادية  في حالة طلب ترخيص\r\nعند قبول عرض يجب وضع المبلغ المقبول في المحظفة لدي المنصة لضمان حق الطرفين",
                'icon_name' => NULL,
            ],

        ];

        DB::table('website_content')->insert($project_page);


        $consult_data = [
            [
                'page_name' => 'consult',
                'page_name_text' => 'صفحة خدمة طلب استشارة',
                'section_name' => 'welcoming',
                'section_name_text' => 'قسم الترحيب',
                'paragraph_name' => 'heading_title',
                'paragraph_name_text' => 'الجملة الرئيسية',
                'content_ar' => 'تعاني مشكلة هندسية ؟ انت تحتاج  لطلب استشارة ',
                'content_en' => 'تعاني مشكلة هندسية ؟ انت تحتاج  لطلب استشارة ',
            ],
            [
                'page_name' => 'consult',
                'page_name_text' => 'صفحة خدمة طلب استشارة',
                'section_name' => 'welcoming',
                'section_name_text' => 'قسم الترحيب',
                'paragraph_name' => 'heading_title2',
                'paragraph_name_text' => 'الفقرة الرئيسية - العنوان',
                'content_ar' => 'نوفر لك دليل المكاتب الهندسية',
                'content_en' => 'نوفر لك دليل المكاتب الهندسية',
            ],
            [
                'page_name' => 'consult',
                'page_name_text' => 'صفحة خدمة طلب استشارة',
                'section_name' => 'welcoming',
                'section_name_text' => 'قسم الترحيب',
                'paragraph_name' => 'welcome_para',
                'paragraph_name_text' => 'الفقرة الرئيسية - النص',
                'content_ar' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام طريقة لوريم إيبسوم لأنها ',
                'content_en' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام طريقة لوريم إيبسوم لأنها ',
            ],

            [
                'page_name' => 'consult',
                'page_name_text' => 'صفحة خدمة طلب استشارة',
                'section_name' => 'why_this_service',
                'section_name_text' => 'لماذا الخدمة',
                'paragraph_name' => 'why',
                'paragraph_name_text' => 'لماذا الخدمة',
                'content_ar' => "اذا كنت تمتلك مشروع هندسي وتواجه مشكلة ولا تعلم ماذا تفعل\r\nاذا كنت ترغب في انشاء مشروع وترغب في استشاري قبل البدء في التنفيذ\r\nإذا كنت قد قمت بإنشاء مخططات لدى مكتب هندسي وترغب في التأكد من سلامة المخططات\r\nقمت بأنجاز المشروع والان تواجه مشكلة وترغب في استشارة مختصين لايجاد حل للمشكلة",
                'content_en' => "اذا كنت تمتلك مشروع هندسي وتواجه مشكلة ولا تعلم ماذا تفعل\r\nاذا كنت ترغب في انشاء مشروع وترغب في استشاري قبل البدء في التنفيذ\r\nإذا كنت قد قمت بإنشاء مخططات لدى مكتب هندسي وترغب في التأكد من سلامة المخططات\r\nقمت بأنجاز المشروع والان تواجه مشكلة وترغب في استشارة مختصين لايجاد حل للمشكلة",
            ],
            [
                'page_name' => 'consult',
                'page_name_text' => 'صفحة خدمة طلب استشارة',
                'section_name' => 'features',
                'section_name_text' => 'مميزات الخدمة',
                'paragraph_name' => 'service_features',
                'paragraph_name_text' => 'الخدمات',
                'content_ar' => "يمكن ان يتم الاستشارة من خلال المهندس المستقل \r\nمهندس محترف - مهندس مستشار - مكتب هندسي \r\nكل جهة لديها ترخيص يتم تحريره كل فترة محددة وبنهاية الترخيص لا يمكن للمكتب الاستفادة من الخدامات إلا بعد الإنتهاء من التجرير والتعامل مع مكتب آخر يعرفه",
                'content_en' => "يمكن ان يتم الاستشارة من خلال المهندس المستقل \r\nمهندس محترف - مهندس مستشار - مكتب هندسي \r\nكل جهة لديها ترخيص يتم تحريره كل فترة محددة وبنهاية الترخيص لا يمكن للمكتب الاستفادة من الخدامات إلا بعد الإنتهاء من التجرير والتعامل مع مكتب آخر يعرفه",
            ],

            [
                'page_name' => 'consult',
                'page_name_text' => 'صفحة خدمة طلب استشارة',
                'section_name' => 'how_we_work',
                'section_name_text' => 'طلب الخدمة',
                'paragraph_name' => 'steps_1',
                'paragraph_name_text' => 'الاشتراك',
                'content_ar' => 'اك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام طريقة لوريم إيبسوم لأنها تعطي توزيعاَ',
                'content_en' => 'اك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام طريقة لوريم إيبسوم لأنها تعطي توزيعاَ',
            ],
            [
                'page_name' => 'consult',
                'page_name_text' => 'صفحة خدمة طلب استشارة',
                'section_name' => 'how_we_work',
                'section_name_text' => 'طلب الخدمة',
                'paragraph_name' => 'steps_2',
                'paragraph_name_text' => 'إضافة الطلب',
                'content_ar' => 'اك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو ',
                'content_en' => 'اك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو ',
            ],
            [
                'page_name' => 'consult',
                'page_name_text' => 'صفحة خدمة طلب استشارة',
                'section_name' => 'how_we_work',
                'section_name_text' => 'طلب الخدمة',
                'paragraph_name' => 'steps_3',
                'paragraph_name_text' => 'استقبال العروض',
                'content_ar' => 'اك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام طريقة لوريم',
                'content_en' => 'اك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام طريقة لوريم',
            ],
            [
                'page_name' => 'consult',
                'page_name_text' => 'صفحة خدمة طلب استشارة',
                'section_name' => 'how_we_work',
                'section_name_text' => 'طلب الخدمة',
                'paragraph_name' => 'steps_4',
                'paragraph_name_text' => 'قبول عرض',
                'content_ar' => 'اك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي',
                'content_en' => 'اك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي',
            ],
            [
                'page_name' => 'consult',
                'page_name_text' => 'صفحة خدمة طلب استشارة',
                'section_name' => 'how_we_work',
                'section_name_text' => 'طلب الخدمة',
                'paragraph_name' => 'steps_5',
                'paragraph_name_text' => 'بدء التواصل',
                'content_ar' => 'اك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في ',
                'content_en' => 'اك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في',
            ],
            [
                'page_name' => 'consult',
                'page_name_text' => 'صفحة خدمة طلب استشارة',
                'section_name' => 'warning_section',
                'section_name_text' => 'قسم التنبيه',
                'paragraph_name' => 'warning_message',
                'paragraph_name_text' => 'التنبيه',
                'content_ar' => "يتم توفير معلومات مبسطة للمسقلين من خلال معرفة تاريخ الترخيص وانتهاؤه والطلبات داخل الموقع - الموقع الجغرافي - بيانات التواصل وغيره\r\nبعد قبول العرض من المكتب الهندسي يتم التواصل بين الطرفين لطلب الرخصة عن طريق (موقع بلدي / الدفاع المدني / البيئة )\r\nالمنصة وسيلة ربط فقط",
                'content_en' => "يتم توفير معلومات مبسطة للمسقلين من خلال معرفة تاريخ الترخيص وانتهاؤه والطلبات داخل الموقع - الموقع الجغرافي - بيانات التواصل وغيره\r\nبعد قبول العرض من المكتب الهندسي يتم التواصل بين الطرفين لطلب الرخصة عن طريق (موقع بلدي / الدفاع المدني / البيئة )\r\nالمنصة وسيلة ربط فقط",
            ],

        ];

        DB::table('website_content')->insert($consult_data);

        $judge_data = [
            [
                'page_name' => 'judge',
                'page_name_text' => 'صفحة خدمة تحكيم بين طرفين',
                'section_name' => 'welcoming',
                'section_name_text' => 'قسم الترحيب',
                'paragraph_name' => 'heading_title',
                'paragraph_name_text' => 'الجملة الرئيسية',
                'content_ar' => "هل تعاني من مشكلة الخلاف بينك وبين طرف اخر؟",
                'content_en' => "هل تعاني من مشكلة الخلاف بينك وبين طرف اخر؟",
            ],

            [
                'page_name' => 'judge',
                'page_name_text' => 'صفحة خدمة تحكيم بين طرفين',
                'section_name' => 'welcoming',
                'section_name_text' => 'قسم الترحيب',
                'paragraph_name' => 'heading_title2',
                'paragraph_name_text' => 'الجملة الرئيسية',
                'content_ar' => "نحن نوفر لك محكم هندسي معتمد و ذو خبرة موثوقة\r\n على أسس علمية وعملية ومعتمد بالهيئة السعودية للمهندسين",
                'content_en' => "نحن نوفر لك محكم هندسي معتمد و ذو خبرة موثوقة\r\n على أسس علمية وعملية ومعتمد بالهيئة السعودية للمهندسين",
            ],


            [
                'page_name' => 'judge',
                'page_name_text' => 'صفحة خدمة تحكيم بين طرفين',
                'section_name' => 'welcoming',
                'section_name_text' => 'قسم الترحيب',
                'paragraph_name' => 'welcome_para',
                'paragraph_name_text' => 'الفقرة الرئيسية - النص',
                'content_ar' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام طريقة لوريم إيبسوم لأنها تعطي توزيعاَ طبيعياَ -إلى حد ما- للأحرف عوضاً عن',
                'content_en' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام طريقة لوريم إيبسوم لأنها تعطي توزيعاَ طبيعياَ -إلى حد ما- للأحرف عوضاً عن',
            ],


            [
                'page_name' => 'judge',
                'page_name_text' => 'صفحة خدمة تحكيم بين طرفين',
                'section_name' => 'why_this_service',
                'section_name_text' => 'لماذا الخدمة',
                'paragraph_name' => 'why',
                'paragraph_name_text' => 'لماذا الخدمة',
                'content_ar' => "خلاف بينك وبين جهة منفذه علي تفاصيل العقد المتفق عليه\r\nخلاف بينك وبين جهة تنفيذ وتشطيب المباني والمنشأت\r\nالمهندس القائم على المشروع قام بخطأ ويرفض تحمل المسؤلية\r\nهناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما",
                'content_en' => "خلاف بينك وبين جهة منفذه علي تفاصيل العقد المتفق عليه\r\nخلاف بينك وبين جهة تنفيذ وتشطيب المباني والمنشأت\r\nالمهندس القائم على المشروع قام بخطأ ويرفض تحمل المسؤلية\r\nهناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما",
            ],

            [
                'page_name' => 'judge',
                'page_name_text' => 'صفحة خدمة تحكيم بين طرفين',
                'section_name' => 'how_we_work',
                'section_name_text' => 'طلب الخدمة',
                'paragraph_name' => 'steps_1',
                'paragraph_name_text' => 'الاشتراك',
                'content_ar' => 'ناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك',
                'content_en' => 'ناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك',
            ],
            [
                'page_name' => 'judge',
                'page_name_text' => 'صفحة خدمة تحكيم بين طرفين',
                'section_name' => 'how_we_work',
                'section_name_text' => 'طلب الخدمة',
                'paragraph_name' => 'steps_2',
                'paragraph_name_text' => 'إضافة الطلب',
                'content_ar' => 'ناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك',
                'content_en' => 'ناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك',
            ],
            [
                'page_name' => 'judge',
                'page_name_text' => 'صفحة خدمة تحكيم بين طرفين',
                'section_name' => 'how_we_work',
                'section_name_text' => 'طلب الخدمة',
                'paragraph_name' => 'steps_3',
                'paragraph_name_text' => 'استقبال العروض',
                'content_ar' => 'ناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك',
                'content_en' => 'ناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك',
            ],
            [
                'page_name' => 'judge',
                'page_name_text' => 'صفحة خدمة تحكيم بين طرفين',
                'section_name' => 'how_we_work',
                'section_name_text' => 'طلب الخدمة',
                'paragraph_name' => 'steps_4',
                'paragraph_name_text' => 'تواصل مع المحكم',
                'content_ar' => 'ناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك',
                'content_en' => 'ناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك',
            ],
            [
                'page_name' => 'judge',
                'page_name_text' => 'صفحة خدمة تحكيم بين طرفين',
                'section_name' => 'how_we_work',
                'section_name_text' => 'طلب الخدمة',
                'paragraph_name' => 'steps_5',
                'paragraph_name_text' => 'انتهاء المشروع',
                'content_ar' => 'ناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك',
                'content_en' => 'ناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك',
            ],



            [
                'page_name' => 'judge',
                'page_name_text' => 'صفحة خدمة تحكيم بين طرفين',
                'section_name' => 'warning_section',
                'section_name_text' => 'قسم التنبيه',
                'paragraph_name' => 'warning_message',
                'paragraph_name_text' => 'التنبيه',
                'content_ar' => "يتم توفير معلومات مبسطة للمسقلين من خلال معرفة تاريخ الترخيص وانتهاؤه والطلبات داخل الموقع - الموقع الجغرافي - بيانات التواصل وغيره\r\nبعد قبول العرض من المكتب الهندسي يتم التواصل بين الطرفين لطلب الرخصة عن طريق (موقع بلدي / الدفاع المدني / البيئة )\r\nالمنصة وسيلة ربط فقط",
                'content_en' => "يتم توفير معلومات مبسطة للمسقلين من خلال معرفة تاريخ الترخيص وانتهاؤه والطلبات داخل الموقع - الموقع الجغرافي - بيانات التواصل وغيره\r\nبعد قبول العرض من المكتب الهندسي يتم التواصل بين الطرفين لطلب الرخصة عن طريق (موقع بلدي / الدفاع المدني / البيئة )\r\nالمنصة وسيلة ربط فقط",
            ],

        ];

        DB::table('website_content')->insert($judge_data);

        $visit_data = [
            [
                'page_name' => 'visit',
                'page_name_text' => 'خدمة طلب زيارة موقع',
                'section_name' => 'welcoming',
                'section_name_text' => 'قسم الترحيب',
                'paragraph_name' => 'heading_title',
                'paragraph_name_text' => 'الجملة الرئيسية',
                'content_ar' => "لديك مشكلة \r\n وترغب بزيارة مهندس مختص لموقعك. ",
                'content_en' => "لديك مشكلة \r\n وترغب بزيارة مهندس مختص لموقعك.؟"
            ],
            [
                'page_name' => 'visit',
                'page_name_text' => 'خدمة طلب زيارة موقع',
                'section_name' => 'welcoming',
                'section_name_text' => 'قسم الترحيب',
                'paragraph_name' => 'heading_title2',
                'paragraph_name_text' => 'الجملة الرئيسية',
                'content_ar' => "أنت في المكان الصحيح 👍",
                'content_en' => "أنت في المكان الصحيح 👍",
            ],
            [
                'page_name' => 'visit',
                'page_name_text' => 'خدمة طلب زيارة موقع',
                'section_name' => 'welcoming',
                'section_name_text' => 'قسم الترحيب',
                'paragraph_name' => 'heading_title3',
                'paragraph_name_text' => 'الجملة الرئيسية',
                'content_ar' => 'دعنا نخبرك .لماذا خدمة طلب زيارة موقع',
                'content_en' => 'دعنا نخبرك .لماذا خدمة طلب زيارة موقع',
            ],
            [
                'page_name' => 'visit',
                'page_name_text' => 'خدمة طلب زيارة موقع',
                'section_name' => 'welcoming',
                'section_name_text' => 'قسم الترحيب',
                'paragraph_name' => 'welcome_para',
                'paragraph_name_text' => 'الفقرة الرئيسية - النص',
                'content_ar' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام طريقة لوريم إيبسوم لأنها تعطي توزيعاَ طبيعياَ -إلى حد ما- للأحرف عوضاً عن استخدام "هنا يوجد محتوى نصي، هنا يوجد محتوى نصي" فتجعلها تبدو (أي الأحرف) وكأنها نص مقروء. العديد من',
                'content_en' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام طريقة لوريم إيبسوم لأنها تعطي توزيعاَ طبيعياَ -إلى حد ما- للأحرف عوضاً عن استخدام "هنا يوجد محتوى نصي، هنا يوجد محتوى نصي" فتجعلها تبدو (أي الأحرف) وكأنها نص مقروء. العديد من',
            ],


            [
                'page_name' => 'visit',
                'page_name_text' => 'خدمة طلب زيارة موقع',
                'section_name' => 'service_features',
                'section_name_text' => 'مميزة الخدمة',
                'paragraph_name' => 'features',
                'paragraph_name_text' => 'مميزة الخدمة',
                'content_ar' => "التأكد من تنفيذ الأعمال حسب المواصفات الفنية المعتمدة\r\nالتأكد من مطابقة المخططات لرخصة البناء\r\nاستشارة هندسية و فنية \r\nتواجه مشكلة في بناء قائم وترغب رؤية المهندس لها على ارض الواقع",
                'content_en' => "التأكد من تنفيذ الأعمال حسب المواصفات الفنية المعتمدة\r\nالتأكد من مطابقة المخططات لرخصة البناء\r\nاستشارة هندسية و فنية \r\nتواجه مشكلة في بناء قائم وترغب رؤية المهندس لها على ارض الواقع",
            ],

            [
                'page_name' => 'visit',
                'page_name_text' => 'خدمة طلب زيارة موقع',
                'section_name' => 'how_we_work',
                'section_name_text' => 'طلب الخدمة',
                'paragraph_name' => 'steps_1',
                'paragraph_name_text' => 'الاشتراك',
                'content_ar' => 'حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات',
                'content_en' => 'حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات',
            ],
            [
                'page_name' => 'visit',
                'page_name_text' => 'خدمة طلب زيارة موقع',
                'section_name' => 'how_we_work',
                'section_name_text' => 'طلب الخدمة',
                'paragraph_name' => 'steps_2',
                'paragraph_name_text' => 'اختيار الخدمة',
                'content_ar' => 'حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات',
                'content_en' => 'حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات',
            ],
            [
                'page_name' => 'visit',
                'page_name_text' => 'خدمة طلب زيارة موقع',
                'section_name' => 'how_we_work',
                'section_name_text' => 'طلب الخدمة',
                'paragraph_name' => 'steps_3',
                'paragraph_name_text' => 'قبول العرض',
                'content_ar' => 'حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات',
                'content_en' => 'حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات',
            ],
            [
                'page_name' => 'visit',
                'page_name_text' => 'خدمة طلب زيارة موقع',
                'section_name' => 'how_we_work',
                'section_name_text' => 'طلب الخدمة',
                'paragraph_name' => 'steps_4',
                'paragraph_name_text' => 'تواصل مع المهندس المستقل/ المكتب الهندسي',
                'content_ar' => 'حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات',
                'content_en' => 'حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات',
            ],

            [
                'page_name' => 'visit',
                'page_name_text' => 'خدمة طلب زيارة موقع',
                'section_name' => 'warning_section',
                'section_name_text' => 'قسم التنبيه',
                'paragraph_name' => 'warning_message',
                'paragraph_name_text' => 'التنبيه',
                'content_ar' => "يتم توفير معلومات مبسطة للمسقلين من خلال معرفة تاريخ الترخيص وانتهاؤه والطلبات داخل الموقع - الموقع الجغرافي - بيانات التواصل وغيره\r\nبعد قبول العرض من المكتب الهندسي يتم التواصل بين الطرفين لطلب الرخصة عن طريق (موقع بلدي / الدفاع المدني / البيئة )\r\nالمنصة وسيلة ربط فقط",
                'content_en' => "يتم توفير معلومات مبسطة للمسقلين من خلال معرفة تاريخ الترخيص وانتهاؤه والطلبات داخل الموقع - الموقع الجغرافي - بيانات التواصل وغيره\r\nبعد قبول العرض من المكتب الهندسي يتم التواصل بين الطرفين لطلب الرخصة عن طريق (موقع بلدي / الدفاع المدني / البيئة )\r\nالمنصة وسيلة ربط فقط",
            ],

        ];

        DB::table('website_content')->insert($visit_data);

        $licence_data = [
            [
                'page_name' => 'licence',
                'page_name_text' => 'خدمة طلب استشارة',
                'section_name' => 'welcoming',
                'section_name_text' => 'قسم الترحيب',
                'paragraph_name' => 'heading_title',
                'paragraph_name_text' => 'الجملة الرئيسية',
                'content_ar' => 'رخص مشروعك وانت قاعد في بيتك',
                'content_en' => 'رخص مشروعك وانت قاعد في بيتك',
            ],
            [
                'page_name' => 'licence',
                'page_name_text' => 'خدمة طلب استشارة',
                'section_name' => 'welcoming',
                'section_name_text' => 'قسم الترحيب',
                'paragraph_name' => 'heading_title2',
                'paragraph_name_text' => 'الجملة الرئيسية',
                'content_ar' => 'لديك مشروع وترغب في اصدار تراخيص له؟ لا تعلم كيف؟او من اين؟',
                'content_en' => 'لديك مشروع وترغب في اصدار تراخيص له؟ لا تعلم كيف؟او من اين؟',
            ],
            [
                'page_name' => 'licence',
                'page_name_text' => 'خدمة طلب استشارة',
                'section_name' => 'what_it_offers',
                'section_name_text' => 'ماذا تقدم لك الخدمة',
                'paragraph_name' => 'what_it_offers_title',
                'paragraph_name_text' => 'الفقرة الرئيسية - النص',
                'content_ar' => 'تساعدك علي اصدار التراخيص للمشاريع المتنوعة بكل سهولة',
                'content_en' => 'تساعدك علي اصدار التراخيص للمشاريع المتنوعة بكل سهولة',
            ],
            [
                'page_name' => 'licence',
                'page_name_text' => 'خدمة طلب استشارة',
                'section_name' => 'what_it_offers',
                'section_name_text' => 'ماذا تقدم لك الخدمة',
                'paragraph_name' => 'what_it_offers_paragraph',
                'paragraph_name_text' => 'الفقرة الرئيسية - النص',
                'content_ar' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام طريقة لوريم إيبسوم لأنها',
                'content_en' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام طريقة لوريم إيبسوم لأنها',
            ],


            [
                'page_name' => 'licence',
                'page_name_text' => 'خدمة طلب استشارة',
                'section_name' => 'exec_agencies',
                'section_name_text' => 'الجهة المنفذه',
                'paragraph_name' => 'exec_agencies_title',
                'paragraph_name_text' => 'الفقرة الرئيسية - النص',
                'content_ar' => 'مجموعة مرخصه من المكاتب التي تقوم بإستخراج التراخيص لك',
                'content_en' => 'مجموعة مرخصه من المكاتب التي تقوم بإستخراج التراخيص لك',
            ],


            [
                'page_name' => 'licence',
                'page_name_text' => 'خدمة طلب استشارة',
                'section_name' => 'exec_agencies',
                'section_name_text' => 'الجهة المنفذه',
                'paragraph_name' => 'exec_agencies_paragraph',
                'paragraph_name_text' => 'الفقرة الرئيسية - النص',
                'content_ar' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام طريقة لوريم إيبسوم لأنها',
                'content_en' => 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام طريقة لوريم إيبسوم لأنها',
            ],




            [
                'page_name' => 'licence',
                'page_name_text' => 'خدمة طلب استشارة',
                'section_name' => 'cons_licence',
                'section_name_text' => 'تراخيص انشاء',
                'paragraph_name' => 'cons_licence1',
                'paragraph_name_text' => 'نوع الترخيص',
                'content_ar' => 'ترخيص انشاء او ترخيص تشغيل',
                'content_en' => 'ترخيص انشاء او ترخيص تشغيل',
            ],


            [
                'page_name' => 'licence',
                'page_name_text' => 'خدمة طلب استشارة',
                'section_name' => 'cons_licence',
                'section_name_text' => 'تراخيص انشاء',
                'paragraph_name' => 'cons_licence2',
                'paragraph_name_text' => 'نوع المشروع',
                'content_ar' => 'قم بختيار نوع المشروع الذي ترغب في ترخيصه',
                'content_en' => 'قم بختيار نوع المشروع الذي ترغب في ترخيصه',
            ],

            [
                'page_name' => 'licence',
                'page_name_text' => 'خدمة طلب استشارة',
                'section_name' => 'cons_licence',
                'section_name_text' => 'تراخيص انشاء',
                'paragraph_name' => 'cons_licence3',
                'paragraph_name_text' => 'التراخيص',
                'content_ar' => 'قم بتحديد التراخيص المطلوبة ، يمكنك طلب ترخيص او عدة تراخيص لمشروع',
                'content_en' => 'قم بتحديد التراخيص المطلوبة ، يمكنك طلب ترخيص او عدة تراخيص لمشروع',
            ],






            [
                'page_name' => 'licence',
                'page_name_text' => 'خدمة طلب استشارة',
                'section_name' => 'oper_licence',
                'section_name_text' => 'تراخيص تشغيل',
                'paragraph_name' => 'oper_licence1',
                'paragraph_name_text' => 'نوع الترخيص',
                'content_ar' => 'ترخيص انشاء او ترخيص تشغيل',
                'content_en' => 'ترخيص انشاء او ترخيص تشغيل',
            ],


            [
                'page_name' => 'licence',
                'page_name_text' => 'خدمة طلب استشارة',
                'section_name' => 'oper_licence',
                'section_name_text' => 'تراخيص تشغيل',
                'paragraph_name' => 'oper_licence2',
                'paragraph_name_text' => 'نوع المشروع',
                'content_ar' => 'قم بختيار نوع المشروع الذي ترغب في ترخيصه',
                'content_en' => 'قم بختيار نوع المشروع الذي ترغب في ترخيصه',
            ],

            [
                'page_name' => 'licence',
                'page_name_text' => 'خدمة طلب استشارة',
                'section_name' => 'oper_licence',
                'section_name_text' => 'تراخيص تشغيل',
                'paragraph_name' => 'oper_licence3',
                'paragraph_name_text' => 'التراخيص',
                'content_ar' => 'قم بتحديد التراخيص المطلوبة ، يمكنك طلب ترخيص او عدة تراخيص لمشروع',
                'content_en' => 'قم بتحديد التراخيص المطلوبة ، يمكنك طلب ترخيص او عدة تراخيص لمشروع',
            ],

            [
                'page_name' => 'licence',
                'page_name_text' => 'خدمة طلب استشارة',
                'section_name' => 'warning_section',
                'section_name_text' => 'قسم التنبيه',
                'paragraph_name' => 'warning_message',
                'paragraph_name_text' => 'التنبيه',
                'content_ar' => "يتم توفير معلومات مبسطة للمسقلين من خلال معرفة تاريخ الترخيص وانتهاؤه والطلبات داخل الموقع - الموقع الجغرافي - بيانات التواصل وغيره\r\nبعد قبول العرض من المكتب الهندسي يتم التواصل بين الطرفين لطلب الرخصة عن طريق (موقع بلدي / الدفاع المدني / البيئة )\r\nالمنصة وسيلة ربط فقط",
                'content_en' => "يتم توفير معلومات مبسطة للمسقلين من خلال معرفة تاريخ الترخيص وانتهاؤه والطلبات داخل الموقع - الموقع الجغرافي - بيانات التواصل وغيره\r\nبعد قبول العرض من المكتب الهندسي يتم التواصل بين الطرفين لطلب الرخصة عن طريق (موقع بلدي / الدفاع المدني / البيئة )\r\nالمنصة وسيلة ربط فقط",
            ],

        ];

        DB::table('website_content')->insert($licence_data);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
        DB::table('website_content')->delete();
    }
}
